<!DOCTYPE html>
<html style="background-color: #1f2b3b" >
<head>
	<title>Личный кабинет</title>
</head>
    <body style="background-color: #f2fafc"> 
       <div class="container-fluid" style="background-color: #2e5179"> 	     
    	<nav class="navbar navbar-dark justify-content-between" style="background-color: #2e5179;">
    				<a href="/myspace" class="navbar-brand">
    					<h1>
    					<p class="text-light">
    					<img src="/public/img/Call.png" width="50" height="50" alt="">
    					Cправочник</p></h1></a>
    					<?php echo $this->tag->form("myspace/exit"); ?>
    				<?php echo $this->tag->linkTo(["phonebook", "Поиск контактов", 'class' => 'btn btn-secondary','style' =>'border: 2px solid black']); ?>
    				<?php echo $this->tag->linkTo(["Myphonebook", "Мои контакты", 'class' => 'btn btn-secondary','style' =>'border: 2px solid black' ]); ?>
    				 <button class="btn btn-secondary" style="border: 2px solid black;"type="submit">Выход</button>
    			</form>
    	</nav>
    	</div>
    	<div style="background-color: #1f2b3b">
<div class="row">
	<div class="col"></div>
	<div class="col">
		<img src="/public/img/Avatar.png" width="250" height="250" alt="" class="rounded mx-auto d-block">
		<h2><p class="text-center text-white"> Имя пользователя: <?php echo $nick ?> </p> </h2>
		<h2><p class="text-center text-white"> Email-адрес: <?php echo $email ?> </p> </h2>
		<?php echo $this->tag->linkTo(["changepass/index", "Изменить пароль", 'class' => 'btn btn-secondary btn-block','style' =>'border: 2px solid black' ]); ?>
	</div>
	<div class="col"></div>
</div>

<div>

	</body>
</html>