<!DOCTYPE html>
<html style="background-color: #1f2b3b">
<head>
	<title>Вход</title>
</head>
<body>
    <nav class="navbar navbar-dark justify-content-between" style="background-color: #2e5179;">
                    <a  class="navbar-brand">
                        <h1>
                        <p class="text-light">
                        <img src="/public/img/Call.png" width="50" height="50" alt="">
                        Cправочник</p></h1></a>
                </form>
        </nav>
	<div class="container-fluid" style="background-color: #1f2b3b">
    <?php echo $this->tag->form("index/signin"); ?>
    <br>
	<br>
    	  <div class="form-group">
    	  	<div class="row">
    	  	<div class="col-md-4"></div>
    	  	<div class="col-md-4" style="background-color: #2e5179; ">
    	  	<h1  class="text-center text-white"> Вход</h1>
            
    		  <label class="text-white" for="email">Email адрес или логин</label>
              <p><?php $this->flash->output() ?></p>
    		  <input type="name" class="form-control" id="email" placeholder="Введите email или логин"  name="email">
    	    </div>
    	  </div>
    	  	<div class="row">
    	  	<div class="col-md-4"></div>
    	  	<div class="col-md-4" style="background-color: #2e5179">
    		  <label for="password"> <a class="text-white">Пароль </a></label> 
    		  <input type="password" class="form-control" id="password" placeholder="Введите пароль" name="password">
    		  <label for="password">
    		  	<input type="checkbox"> <a class="text-white">Сохранить пароль?</a>
    		  </label>
    		  <br>
    		  <?php echo $this->tag->submitButton(["Вход", 'class' => 'btn btn-secondary btn-block','style' =>'border: 2px solid black']); ?>
    		  </form>
    		  <br>
    		 <?php echo $this->tag->linkTo(["signup", "Зарегестрироваться", 'class' => 'btn btn-secondary btn-block','style' =>'border: 2px solid black']); ?>
    		  <br>
    	    </div>
    	  </div>
    	  </div>
    	</div>
    	</div>
    </div>
</body>
</html>
