<!DOCTYPE html>
<html>
<head>
	<title>Вход</title>
</head>
<body>
	<br>
	<br>
	<br>
	<div class="container-fluid">
    <?php echo $this->tag->form("index/signin"); ?>
    <br>
	<br>
    	  <div class="form-group">
    	  	<div class="row">
    	  	<div class="col-md-4"></div>
    	  	<div class="col-md-4" style="background-color: silver; ">
    	  	<h1 class="text-center"> Справочник</h1>
            
    		  <label for="email">Email адрес</label>
              <p><?php $this->flash->output() ?></p>
    		  <input type="email" class="form-control" id="email" placeholder="Введите email"  name="email">
    	    </div>
    	  </div>
    	  	<div class="row">
    	  	<div class="col-md-4"></div>
    	  	<div class="col-md-4" style="background-color: silver">
    		  <label for="password">Пароль</label>
    		  <input type="password" class="form-control" id="password" placeholder="Введите пароль" name="password">
    		  <label for="password">
    		  	<input type="checkbox"> Сохранить пароль?
    		  </label>
    		  <br>
    		  <?php echo $this->tag->submitButton(["Вход", 'class' => 'btn btn-success  btn-block']); ?>
    		  </form>
    		  <br>
    		 <?php echo $this->tag->linkTo(["signup", "Зарегестрироваться", 'class' => 'btn btn-primary btn-block']); ?>
    		  <br>
    	    </div>
    	  </div>
    	  </div>
    	</div>
    	</div>
    </div>
</body>
</html>
