
<table>
<thead>
<tr>
<th>Id</th>
<th>Имя</th>
<th>Телефон</th>

</tr>
</thead>
<tbody>

<?php

foreach($page->GetItems() as $people){
echo '
<tr>
<td>'.$people["id"].' </td>
<td>'.$people["name"].' </td>
<td>'.$this->tag->linkTo("phonebook/delete/".$people["id"], "Удалить").'</td>
</tr>';
}

echo '
</tbody>
<tbody>
<tr>
<td colspan="7">
<div>';
echo $this->tag->linkTo("phonebook/search", "Первая");
echo $this->tag->linkTo("phonebook/search?page=".$page->previous, "Предыдущая");
echo $this->tag->linkTo("phonebook/search?page=".$page->next, "Следующая");
echo $this->tag->linkTo("phonebook/search?page=".$page->last, "Последняя");

echo '<span class="help-inline">'.$page->current.' из'. $page->last .'</span>
</div>
</td>
</tr>
</tbody>
</table>';


?>