
<style>
   .accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 50%;
  text-align: center;
  border: none;
  outline: none;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc;
}


.panel {
  padding: 0 18px;
  background-color: white;
  display: none;
  overflow: hidden;
  
}
input[type=text] {
	
	width: 50%;
	border: none;
	border-bottom: 2px solid grey;
 
}
#address {
	display:inline-block;
    width: 12%; 
   } 
</style>
  
  



<?php

	foreach($page->GetItems() as $people){
	echo '<button class="accordion">'.$people->getPeople()->name.' ';
	
	echo $people->phoneNumber.'</button>';
	

	echo '
		<div class="panel">
		<p>';
		echo $this->tag->form("phonebook/edit");
		echo '
		<input type="text" class="form-control" value='.$people->phoneNumber.' placeholder='.$people->phoneNumber.'  name="phone">
		<input type="text" class="form-control" value='.$people->getPeople()->name.' placeholder='.$people->getPeople()->name.'  name="name">
		<input type="text" class="form-control" value='.$people->getPeople()->secondName.' placeholder='.$people->getPeople()->secondName.'  name="secondName">
		<input type="text" class="form-control" value='.$people->getPeople()->patronomic.' placeholder='.$people->getPeople()->patronomic.'  name="fatherName">
		<input type="text" class="form-control" value='.$people->getPeople()->mail.' placeholder='.$people->getPeople()->mail.'  name="mail">
		<input type="text" class="form-control" value='.$people->getPeople()->organizationName.' placeholder='.$people->getPeople()->organizationName.'  name="orgName">
		<input type="text" class="form-control" id="address" value='.$people->getPeople()->city.' placeholder='.$people->getPeople()->city.'  name="city">
		<input type="text" class="form-control" id="address" value='.$people->getPeople()->street.' placeholder='.$people->getPeople()->street.'  name="street">
		<input type="text" class="form-control" id="address" value='.$people->getPeople()->house.' placeholder='.$people->getPeople()->house.'  name="house">
		<input type="text" class="form-control" id="address" value='.$people->getPeople()->apNumber.' placeholder='.$people->getPeople()->apNumber.'  name="ap">
		
		
		';
		echo $this->tag->submitButton("Изменить");
		echo '</form>';
		echo '<br>';
		echo $this->tag->linkTo("phonebook/delete/".$people->phoneNumber, "Удалить").'
		</p>
		
		</div>';
	}

	echo '
	</tbody>
	<tbody>
	<tr>
	<td colspan="7">
	<div>';
	echo $this->tag->linkTo("phonebook/search", "Первая").' ';
	echo $this->tag->linkTo("phonebook/search?page=".$page->previous, "Предыдущая").' ';
	echo $this->tag->linkTo("phonebook/search?page=".$page->next, "Следующая").' ';
	echo $this->tag->linkTo("phonebook/search?page=".$page->last, "Последняя").' ';
	echo '<br>';
	echo '<span class="help-inline">'.$page->current.' из '. $page->last .'</span>
	</div>
	</td>
	</tr>
	</tbody>
	</table>';


?>
<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    
    this.classList.toggle("active");

    var panel = this.nextElementSibling;
    if (panel.style.display === "block") {
      panel.style.display = "none";
    } else {
      panel.style.display = "block";
    }
  });
}
</script>
